#!/usr/bin/env node
var debug = require('debug')('app4weixin');
var app = require('./app');

app.set('port', process.env.PORT || 3000);
var port = app.get('port');
var server = app.listen(port, function() {
  debug('Express server listening on port ' + server.address().port);
  console.log('Express server listening on port ' + port);
});
